services:
    api.json.render.service:
        class: Api\ApiBundle\Service\JsonRenderService
        calls:
            - [setContainer, ['@service_container']]
#    api.example:
#        class: Api\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
