<?php

namespace Core\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
    public function findCountQuestionBySpace($space)
    {
        $qb = $this->createQueryBuilder('q');

        $qb
            ->join('CoreBundle:Space', 's', 'WITH', 's.id = q.space')
            ->where('q.space = :space')->setParameter('space', $space)
        ;
        return $qb->getQuery()->getResult();
    }

    public function searchQuestion($key)
    {
        $qb = $this->createQueryBuilder('q');

        $qb
            ->where('q.title LIKE :key OR q.description LIKE :key')->setParameter('key', '%'.$key.'%');
        ;
        return $qb->getQuery()->getResult();
    }
}
