<?php

namespace Core\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SpaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpaceRepository extends EntityRepository
{
}
